name:          "WTF, HTML e CSS?"
url:           http://uncasually.github.io/wtf-html-css/
repo:          https://github.com/uncasually/wtf-html-css
twitter:       https://twitter.com/uncasually


markdown:      kramdown
permalink:     pretty
highlighter:   rouge
